// Shared math-expression compiler. Used by every graph-choice renderer
// (vectorField / contour / region / parametric / surface) and by
// validateQuestion. The dialect is the same simple subset Phase 1 picked:
//   + - * / ^ , parens
//   sin cos tan exp log ln sqrt abs atan asin acos sinh cosh tanh
//   min max pow floor ceil round sign
//   pi  E
//
// We compile expressions via Function() rather than pulling in a runtime
// math library — vector-field / surface / contour expressions in this app
// are simple polynomial / trig forms generated by the Claude prompt.

function _toJs(expr) {
  return String(expr)
    .replace(/\^/g, "**")
    .replace(/\b(sin|cos|tan|exp|log|ln|sqrt|abs|atan|asin|acos|sinh|cosh|tanh|min|max|pow|floor|ceil|round|sign)\b/g, m => m === "ln" ? "Math.log" : `Math.${m}`)
    .replace(/\bpi\b/gi, "Math.PI")
    .replace(/\bE\b/g, "Math.E");
}

// Compile expr into a function of paramNames. Returns null if unparseable
// or if a probe call throws / returns non-numeric. Probe values default to
// 0.5 for each parameter — chosen to avoid the singularities at 0 that
// 1/x-style expressions would hit.
export function compileExpression(expr, paramNames = ["x", "y"]) {
  if (typeof expr !== "string" || !expr.trim()) return null;
  try {
    const fn = new Function(...paramNames, `"use strict"; return (${_toJs(expr)});`);
    const probe = fn(...paramNames.map(() => 0.5));
    if (typeof probe !== "number" && typeof probe !== "boolean") return null;
    return fn;
  } catch (_e) {
    return null;
  }
}

// Quick "is this expression syntactically + numerically usable" check for
// the validator. Stricter than compileExpression — requires the probe to
// return a finite number.
export function isExpressionValid(expr, paramNames = ["x", "y"]) {
  const fn = compileExpression(expr, paramNames);
  if (!fn) return false;
  try {
    const v = fn(...paramNames.map(() => 0.5));
    return typeof v === "number" && isFinite(v);
  } catch (_e) {
    return false;
  }
}
