// Shared math-expression compiler. Used by every graph-choice renderer
// (vectorField / contour / region / parametric / surface) and by
// validateQuestion. The dialect is the same simple subset Phase 1 picked:
//   + - * / ^ , parens
//   sin cos tan exp log ln sqrt abs atan asin acos sinh cosh tanh
//   min max pow floor ceil round sign
//   pi  E
//
// We compile expressions via Function() rather than pulling in a runtime
// math library — vector-field / surface / contour expressions in this app
// are simple polynomial / trig forms generated by the Claude prompt.

// Insert explicit `*` between number-letter, number-paren, and paren-letter
// pairs so that mathematician-style "2x", "3sin(x)", "(x+1)y", "2(x+1)"
// all compile. The Claude prompt asks for "2*x" but the model reverts to
// implicit multiplication often enough that we treat it as the canonical
// form and normalize on the way in. We deliberately do NOT insert `*`
// between adjacent letters ("xy") — that would shred function names like
// `sin`, `cos`, `sqrt`, and the math evaluator's whitelist already forces
// callers to write multi-letter products explicitly.
export function autofixImplicitMultiplication(expr) {
  if (typeof expr !== "string") return expr;
  let s = expr;
  // digit followed by letter / underscore / `(` → insert `*`
  s = s.replace(/(\d)([a-zA-Z_(])/g, "$1*$2");
  // closing `)` followed by letter / digit / `(` → insert `*`
  s = s.replace(/\)([a-zA-Z0-9_(])/g, ")*$1");
  return s;
}

// JS forbids a unary +/- as the LEFT operand of ** ("-2**x" is a SyntaxError),
// but standard math notation -2^x means -(2^x) — unary minus binds LOOSER than
// exponentiation. After ^→** translation, wrap each power `base**exp` in parens
// so a preceding unary sign stays OUTSIDE the power: -2**x → -(2**x) (= -4 at 2),
// not (-2)**x (= 4). This is value-NEUTRAL — it only adds grouping around the
// power itself. Covers number / identifier (incl. dotted Math.x and simple
// call) / parenthesized bases, with number / group / identifier exponents; runs
// to a fixed point for chains. Exported so the renderer's evalFn shares it
// EXACTLY (graph and answer key must never diverge).
export function wrapExponentBases(jsExpr) {
  let s = String(jsExpr);
  const EXP = "(-?\\d+(?:\\.\\d+)?|\\([^()]+\\)|[A-Za-z_][\\w.]*(?:\\([^()]*\\))?)";
  // One sequential pass per base kind. The patterns are applied once each (not to
  // a fixed point) so an already-wrapped power "(2**x)" is never re-wrapped — each
  // distinct power in the expression is parenthesized exactly once.
  const patterns = [
    // (group) ** exp
    new RegExp("(\\([^()]*\\))\\s*\\*\\*\\s*" + EXP, "g"),
    // identifier / dotted / simple-call ** exp   (e.g. x**2, Math.sqrt(x)**2)
    new RegExp("(?<![.\\w)])([A-Za-z_][\\w.]*(?:\\([^()]*\\))?)\\s*\\*\\*\\s*" + EXP, "g"),
    // number ** exp   (e.g. 2**x, 2**(x))
    new RegExp("(?<![.\\w)])(\\d+(?:\\.\\d+)?)\\s*\\*\\*\\s*" + EXP, "g"),
  ];
  for (const re of patterns) s = s.replace(re, "($1**$2)");
  return s;
}

// Log convention for this compiler (choice-graph renderers + validateQuestion):
//   ln    → Math.log    (natural log)
//   bare "log" → Math.log (NATURAL log, via the Math.${m} fallthrough)
// This DIVERGES from the stem renderer in lib/exports/graphRendering.js, where
// bare "log" = base-10 (Math.log10). The divergence is intentionally left
// unchanged here (changing it would silently alter every choice-graph / validator
// result); documented so callers know "log" is base-dependent on the render path.
function _toJs(expr) {
  let s = autofixImplicitMultiplication(String(expr)).replace(/\^/g, "**");
  s = wrapExponentBases(s);
  return s
    .replace(/\b(sin|cos|tan|exp|log|ln|sqrt|abs|atan|asin|acos|sinh|cosh|tanh|min|max|pow|floor|ceil|round|sign)\b/g, m => m === "ln" ? "Math.log" : `Math.${m}`)
    .replace(/\bpi\b/gi, "Math.PI")
    .replace(/\bE\b/g, "Math.E");
}

// Compile expr into a function of paramNames. Returns null if unparseable
// or if a probe call throws / returns non-numeric. Probe values default to
// 0.5 for each parameter — chosen to avoid the singularities at 0 that
// 1/x-style expressions would hit.
export function compileExpression(expr, paramNames = ["x", "y"]) {
  if (typeof expr !== "string" || !expr.trim()) return null;
  try {
    const fn = new Function(...paramNames, `"use strict"; return (${_toJs(expr)});`);
    const probe = fn(...paramNames.map(() => 0.5));
    if (typeof probe !== "number" && typeof probe !== "boolean") return null;
    return fn;
  } catch (_e) {
    return null;
  }
}

// Quick "is this expression syntactically + numerically usable" check for
// the validator. Stricter than compileExpression — requires the probe to
// return a finite number.
export function isExpressionValid(expr, paramNames = ["x", "y"]) {
  const fn = compileExpression(expr, paramNames);
  if (!fn) return false;
  try {
    const v = fn(...paramNames.map(() => 0.5));
    return typeof v === "number" && isFinite(v);
  } catch (_e) {
    return false;
  }
}
