const fs = require('fs');
const file = 'C:/Users/Mohammad/testbank-pro/testbank-pro/components/TestBankApp.js';
const lines = fs.readFileSync(file, 'utf8').split('\n');

// Find the line indices
let readyToBuildIdx = -1, versionsGt0Idx = -1;
for (let i = 0; i < lines.length; i++) {
  if (lines[i].includes('READY TO BUILD panel')) readyToBuildIdx = i;
  if (lines[i].includes('versions.length > 0 && (')) versionsGt0Idx = i;
}
console.log('READY TO BUILD idx:', readyToBuildIdx, '(line', readyToBuildIdx+1+')');
console.log('versions.length > 0 idx:', versionsGt0Idx, '(line', versionsGt0Idx+1+')');

// prefix = lines before the READY TO BUILD panel
const prefix = lines.slice(0, readyToBuildIdx);

// stage4 = from the versions.length > 0 line onwards (rest of file)
const stage4 = lines.slice(versionsGt0Idx);
// Change versions.length > 0 to versions.length > 1 on the first line
stage4[0] = stage4[0].replace('versions.length > 0', 'versions.length > 1');

// New Stage 1 + 2 + 3 content
const newStages = [
  "            {/* \u2500\u2500 STAGE 1: Questions selected, ready to create master \u2500\u2500 */}",
  "            {versions.length === 0 && selectedForExam.length > 0 && (() => {",
  "              const selected = bank",
  "                .filter(q => selectedForExam.includes(q.id))",
  "                .sort((a,b) => {",
  "                  const [aMaj, aMin] = sectionSortKey(a.section);",
  "                  const [bMaj, bMin] = sectionSortKey(b.section);",
  "                  return aMaj !== bMaj ? aMaj - bMaj : aMin - bMin;",
  "                });",
  "              return (",
  "                <div>",
  "                  <div style={{...S.card, borderColor:accent+\"44\", marginBottom:\"1rem\"}}>",
  "                    <div style={{display:\"flex\", alignItems:\"center\", justifyContent:\"space-between\", marginBottom:\"0.75rem\", flexWrap:\"wrap\", gap:\"0.5rem\"}}>",
  "                      <div>",
  "                        <div style={{fontSize:\"0.95rem\", fontWeight:\"600\", color:text1, marginBottom:\"0.2rem\"}}>",
  "                          {selected.length} questions selected",
  "                        </div>",
  "                        <div style={{fontSize:\"0.72rem\", color:text2}}>",
  "                          {[...new Set(selected.map(q => q.course))].join(\", \")} \u00b7 {[...new Set(selected.map(q => q.section))].length} sections",
  "                        </div>",
  "                      </div>",
  "                      <button style={S.ghostBtn(\"#f87171\")} onClick={() => setSelectedForExam([])}>",
  "                        \u2715 Clear selection",
  "                      </button>",
  "                    </div>",
  "                    <div style={{display:\"flex\", flexDirection:\"column\", gap:\"0.3rem\", marginBottom:\"1rem\"}}>",
  "                      {selected.map((q,i) => (",
  "                        <div key={q.id} style={{display:\"flex\", alignItems:\"center\", gap:\"0.5rem\", padding:\"0.35rem 0\", borderBottom: i < selected.length-1 ? \"1px solid \"+border+\"44\" : \"none\"}}>",
  "                          <span style={S.diffTag(q.difficulty||\"\")}>{(q.difficulty||\"\u003f\")[0]}</span>",
  "                          <span style={{...S.tag(courseColors[q.course]), flexShrink:0}}>{(q.section||\"\").split(\" \").slice(0,2).join(\" \")}</span>",
  "                          <span style={{fontSize:\"0.8rem\", color:text2, flex:1, overflow:\"hidden\", textOverflow:\"ellipsis\", whiteSpace:\"nowrap\"}}>",
  "                            {q.type===\"Branched\" ? q.stem : q.question}",
  "                          </span>",
  "                          <button style={{...S.smBtn, color:\"#f87171\", border:\"none\", padding:\"0.1rem 0.3rem\"}}",
  "                            onClick={() => setSelectedForExam(p => p.filter(id => id !== q.id))}>\u2715</button>",
  "                        </div>",
  "                      ))}",
  "                    </div>",
  "                    <button",
  "                      style={{...S.btn(\"#10b981\", false), fontSize:\"0.88rem\", padding:\"0.55rem 1.4rem\"}}",
  "                      onClick={() => {",
  "                        setVersions([{ label: \"A\", questions: selected }]);",
  "                        setActiveVersion(0);",
  "                        setMasterLocked(false);",
  "                      }}>",
  "                      \u2746 Create Master Exam (Version A)",
  "                    </button>",
  "                  </div>",
  "                </div>",
  "              );",
  "            })()}",
  "",
  "            {/* \u2500\u2500 STAGE 2: Master Version A created \u2014 proof and verify \u2500\u2500 */}",
  "            {versions.length === 1 && !masterLocked && (() => {",
  "              const v = versions[0];",
  "              return (",
  "                <div>",
  "                  <div style={{background:\"#451a0322\", border:\"1px solid #f59e0b44\", borderRadius:\"8px\", padding:\"0.75rem 1rem\", marginBottom:\"1.25rem\", display:\"flex\", alignItems:\"center\", gap:\"0.75rem\", flexWrap:\"wrap\"}}>",
  "                    <span style={{fontSize:\"1.1rem\"}}>\u26a0\ufe0f</span>",
  "                    <div style={{flex:1}}>",
  "                      <div style={{fontSize:\"0.82rem\", fontWeight:\"600\", color:\"#f59e0b\"}}>Export and proof your master exam before generating variants</div>",
  "                      <div style={{fontSize:\"0.72rem\", color:text3, marginTop:\"0.2rem\"}}>Edit any question below, then click \u201cMaster Verified\u201d when you\u2019re satisfied with Version A.</div>",
  "                    </div>",
  "                  </div>",
  "                  <div style={{display:\"flex\", gap:\"0.75rem\", marginBottom:\"1.25rem\", flexWrap:\"wrap\"}}>",
  "                    <button style={S.btn(\"#10b981\", exportLoading !== \"\")} disabled={exportLoading !== \"\"} onClick={async () => {",
  "                      setExportLoading(\"Building Word document...\");",
  "                      try {",
  "                        const blob = await buildDocx(v.questions, v.questions[0]?.course||\"Calculus\", v.label, null);",
  "                        dlBlob(blob, `Version_A_Master_Exam.docx`);",
  "                      } finally { setExportLoading(\"\"); }",
  "                    }}>\u2b07 Word (.docx)</button>",
  "                    <button style={S.oBtn(\"#06b6d4\")} onClick={() => setShowPrintPreview(true)}>",
  "                      \ud83d\udc41 Print Preview",
  "                    </button>",
  "                    <button style={S.oBtn(\"#f43f5e\")} disabled={exportLoading !== \"\"} onClick={async () => {",
  "                      setExportLoading(\"Building answer key...\");",
  "                      try {",
  "                        const blob = await buildAnswerKey([v], v.questions[0]?.course || \"Exam\");",
  "                        if (blob) dlBlob(blob, `Version_A_Answer_Key.docx`);",
  "                      } finally { setExportLoading(\"\"); }",
  "                    }}>\ud83d\udd11 Answer Key (.docx)</button>",
  "                    <button style={S.oBtn(\"#8b5cf6\")} onClick={async () => {",
  "                      const xml = buildQTI(v.questions, v.questions[0]?.course||\"Exam\", v.label, qtiUseGroups, qtiPointsPerQ);",
  "                      const blob = await buildQTIZip(xml, `Version_A`);",
  "                      dlBlob(blob, `Version_A_Canvas_QTI.zip`);",
  "                    }}>\u2b07 QTI (.zip)</button>",
  "                    {exportLoading && <span style={{fontSize:\"0.75rem\", color:text3, alignSelf:\"center\"}}>\u23f3 {exportLoading}</span>}",
  "                  </div>",
  "                  {v.questions.map((q,qi) => (",
  "                    <div key={q.id||qi} style={S.qCard}>",
  "                      <div style={S.qMeta}>",
  "                        <span style={{fontWeight:\"bold\", color:text1}}>Q{qi+1}</span>",
  "                        <span style={S.tag(\"#f43f5e\")}>{q.type}</span>",
  "                        <span style={S.tag()}>{q.section}</span>",
  "                        <span style={S.tag()}>{q.difficulty}</span>",
  "                        <div style={{marginLeft:\"auto\", display:\"flex\", gap:\"0.3rem\"}}>",
  "                          <button style={{...S.smBtn, color: inlineEditQId===`master_${qi}` ? \"#60a5fa\" : \"#a78bfa\", border:\"1px solid #a78bfa44\"}}",
  "                            onClick={() => setInlineEditQId(inlineEditQId===`master_${qi}` ? null : `master_${qi}`)}>",
  "                            \u270f\ufe0f",
  "                          </button>",
  "                        </div>",
  "                      </div>",
  "                      {inlineEditQId === `master_${qi}` && (",
  "                        <InlineEditor",
  "                          q={q}",
  "                          onSave={(updated) => {",
  "                            setVersions([{ ...v, questions: v.questions.map((vq,vqi) => vqi !== qi ? vq : updated) }]);",
  "                            setInlineEditQId(null);",
  "                            showToast(\"Question updated \u2713\");",
  "                          }}",
  "                          onClose={() => setInlineEditQId(null)}",
  "                        />",
  "                      )}",
  "                      {q.type===\"Branched\" ? (",
  "                        <>",
  "                          <div style={{...S.qText,color:\"#f43f5e99\"}}>Given: <MathText>{q.stem}</MathText></div>",
  "                          {(q.parts||[]).map((p,pi) => (",
  "                            <div key={pi} style={{marginBottom:\"0.6rem\",paddingLeft:\"0.75rem\",borderLeft:\"2px solid \"+border}}>",
  "                              <div style={{fontSize:\"0.7rem\",color:text3,marginBottom:\"0.2rem\"}}>({String.fromCharCode(97+pi)})</div>",
  "                              <div style={S.qText}><MathText>{p.question}</MathText></div>",
  "                              {p.answer&&<div style={S.ans}>Answer: <MathText>{p.answer}</MathText></div>}",
  "                              {p.explanation&&<div style={S.expl}>\ud83d\udca1 <MathText>{p.explanation}</MathText></div>}",
  "                            </div>",
  "                          ))}",
  "                        </>",
  "                      ) : (",
  "                        <>",
  "                          <div style={S.qText}><MathText>{q.question}</MathText></div>",
  "                          {q.choices&&<ul style={S.cList}>{q.choices.map((c,ci)=><li key={ci} style={S.cItem(c===q.answer)}>{String.fromCharCode(65+ci)}. <MathText>{c}</MathText></li>)}</ul>}",
  "                          {q.answer&&<div style={S.ans}>\u2713 <MathText>{q.answer}</MathText></div>}",
  "                          {q.explanation&&<div style={S.expl}>\ud83d\udca1 <MathText>{q.explanation}</MathText></div>}",
  "                        </>",
  "                      )}",
  "                    </div>",
  "                  ))}",
  "                  <div style={{marginTop:\"1.5rem\", padding:\"1rem\", background:\"#052e1688\", borderRadius:\"8px\", border:\"1px solid #22c55e44\", display:\"flex\", alignItems:\"center\", gap:\"1rem\", flexWrap:\"wrap\"}}>",
  "                    <div style={{flex:1}}>",
  "                      <div style={{fontSize:\"0.85rem\", fontWeight:\"600\", color:\"#4ade80\"}}>Ready to generate variants?</div>",
  "                      <div style={{fontSize:\"0.72rem\", color:text3, marginTop:\"0.2rem\"}}>This will lock Version A and let you configure B, C, D variants.</div>",
  "                    </div>",
  "                    <button",
  "                      style={{...S.btn(\"#10b981\", false), fontSize:\"0.88rem\", padding:\"0.55rem 1.4rem\"}}",
  "                      onClick={() => setMasterLocked(true)}>",
  "                      \u2705 Master Verified \u2014 Generate Variants",
  "                    </button>",
  "                  </div>",
  "                </div>",
  "              );",
  "            })()}",
  "",
  "            {/* \u2500\u2500 STAGE 3: Master verified \u2014 configure variants \u2500\u2500 */}",
  "            {versions.length === 1 && masterLocked && (",
  "              <div>",
  "                <div style={{...S.card, borderColor:\"#10b98144\", marginBottom:\"1rem\"}}>",
  "                  <div style={{fontSize:\"0.78rem\", color:\"#10b981\", fontWeight:\"700\", marginBottom:\"0.75rem\"}}>",
  "                    \u2705 Version A locked \u00b7 Now configure variants (B, C, D\u2026)",
  "                  </div>",
  "                  <div style={{display:\"flex\", gap:\"1rem\", flexWrap:\"wrap\", alignItems:\"flex-end\"}}>",
  "                    <div>",
  "                      <div style={S.lbl}>Variants to generate</div>",
  "                      <select style={{...S.sel, width:\"160px\"}} value={versionCount} onChange={e => setVersionCount(Number(e.target.value))}>",
  "                        {[1,2,3,4].map(n => {",
  "                          const lbls = VERSIONS.slice(1, 1+n);",
  "                          return <option key={n} value={n}>{n} variant{n>1?\"s\":\"\"} ({lbls.join(\", \")})</option>;",
  "                        })}",
  "                      </select>",
  "                    </div>",
  "                    <div>",
  "                      <div style={S.lbl}>Classroom sections</div>",
  "                      <input type=\"number\" min={1} max={10} value={numClassSections}",
  "                        style={{...S.input, width:\"80px\"}}",
  "                        onChange={e => setNumClassSections(Math.max(1, Number(e.target.value)||1))} />",
  "                    </div>",
  "                    <button style={S.btn(accent, false)} onClick={triggerVersions}>",
  "                      \u2746 {numClassSections > 1 ? `Generate All ${numClassSections} Sections` : \"Generate Variants\"}",
  "                    </button>",
  "                  </div>",
  "                </div>",
  "                {pendingType === \"version_all\" && generatedPrompt && (",
  "                  <>",
  "                    <div style={{fontSize:\"0.78rem\", color:accent, fontWeight:\"600\", marginBottom:\"0.5rem\"}}>",
  "                      \ud83d\udccb Copy this prompt \u2014 paste to Claude \u2014 paste response back:",
  "                    </div>",
  "                    <div style={S.promptBox}>{generatedPrompt}</div>",
  "                    <div style={{display:\"flex\", gap:\"0.75rem\", marginBottom:\"1rem\", flexWrap:\"wrap\"}}>",
  "                      <button style={{...S.btn(\"#10b981\", autoGenLoading), minWidth:\"160px\"}}",
  "                        disabled={autoGenLoading}",
  "                        onClick={() => autoGenerateVersions(generatedPrompt, pendingType, pendingMeta)}>",
  "                        {autoGenLoading ? \"\u23f3 Generating...\" : \"\u26a1 Generate Variants\"}",
  "                      </button>",
  "                      {isAdmin && <button style={S.oBtn(accent)} onClick={() => navigator.clipboard.writeText(generatedPrompt)}>Copy Prompt</button>}",
  "                    </div>",
  "                    {autoGenError && <div style={{color:\"#f87171\", fontSize:\"0.78rem\", marginBottom:\"0.75rem\"}}>{autoGenError}</div>}",
  "                    <PastePanel",
  "                      label=\"Paste Claude's JSON response here.\"",
  "                      S={S} text2={text2}",
  "                      pasteInput={pasteInput} setPasteInput={setPasteInput}",
  "                      pasteError={pasteError} handlePaste={handlePaste}",
  "                      onCancel={() => { setPendingType(null); setPasteInput(\"\"); setGeneratedPrompt(\"\"); }}",
  "                    />",
  "                  </>",
  "                )}",
  "                {pendingType === \"version_all_sections\" && generatedPrompt && (",
  "                  <>",
  "                    <div style={{fontSize:\"0.78rem\", color:accent, fontWeight:\"600\", marginBottom:\"0.5rem\"}}>",
  "                      \ud83d\udccb Copy this prompt \u2014 generates ALL {pendingMeta?.numClassSections} sections \u00d7 {pendingMeta?.labels?.join(\", \")} versions in one go:",
  "                    </div>",
  "                    <div style={S.promptBox}>{generatedPrompt}</div>",
  "                    <div style={{display:\"flex\", gap:\"0.75rem\", marginBottom:\"1rem\", flexWrap:\"wrap\"}}>",
  "                      <button style={{...S.btn(\"#10b981\", autoGenLoading), minWidth:\"160px\"}}",
  "                        disabled={autoGenLoading}",
  "                        onClick={() => autoGenerateVersions(generatedPrompt, pendingType, pendingMeta)}>",
  "                        {autoGenLoading ? \"\u23f3 Generating...\" : \"\u26a1 Generate Variants\"}",
  "                      </button>",
  "                      {isAdmin && <button style={S.oBtn(accent)} onClick={() => navigator.clipboard.writeText(generatedPrompt)}>Copy Prompt</button>}",
  "                    </div>",
  "                    {autoGenError && <div style={{color:\"#f87171\", fontSize:\"0.78rem\", marginBottom:\"0.75rem\"}}>{autoGenError}</div>}",
  "                    <PastePanel",
  "                      label=\"Paste the combined JSON response (all sections + versions).\"",
  "                      S={S} text2={text2}",
  "                      pasteInput={pasteInput} setPasteInput={setPasteInput}",
  "                      pasteError={pasteError} handlePaste={handlePaste}",
  "                      onCancel={() => { setPendingType(null); setPasteInput(\"\"); setGeneratedPrompt(\"\"); }}",
  "                    />",
  "                  </>",
  "                )}",
  "              </div>",
  "            )}",
  "",
  "            {/* \u2500\u2500 STAGE 4: Variants generated \u2014 full export and compare flow \u2500\u2500 */}"
];

const newLines = [
  ...prefix,
  ...newStages,
  ...stage4
];

fs.writeFileSync(file, newLines.join('\n'), 'utf8');
console.log('Done. New line count:', newLines.length);
